apiVersion: v1
kind: Pod
metadata:
    name: token-server
    labels:
        app: token-server
spec:
    volumes:
    - name: html
      emptyDir: {}
    - name: config
      configMap:
        name: token-server-conf
        items:
        - key: nginx-conf.conf
          path: nginx.conf      
    containers:
        - name: uuidgen
          image: aneeshpadmanabhan/uuidgen
          env:
          - name: INTERVAL
            valueFrom:
                configMapKeyRef:
                    name: token-server-conf
                    key: sleep_interval
          args: ["$(INTERVAL)"]
          volumeMounts:
          - name: html
            mountPath: /htdocs
        - name: web-server
          image: nginx:alpine
          ports:
          - containerPort: 80
            protocol: TCP
          volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
            readOnly: true
          - name: config
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: config
            mountPath: /etc/custom-nginx.conf
            subPath: nginx.conf
          livenessProbe:
              httpGet:
                  path: /
                  port: 80
